### PR TITLE
Updated tutorial to latest versions

### PR DESCRIPTION
**Pull request by jpkrohling**
This PR updates the scenarios to work with the latest changes to be introduced by @SevaSafris on the tutorial this is based on (https://github.com/yurishkuro/opentracing-tutorial/pull/30).

This should be merged whenever that one is merged, to avoid the scenarios from being broken.

@SevaSafris, could you take a quick look at this one and see if this matches with your changes?

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by safris** [comment]
@jpkrohling, the changes to scenarios seem aligned to the work I did with the opentracing-tutorial. One comment though: tracer.close() still needs to be called. I ended up putting the JaegerTracer init in a try-resource block.

**Comment by jpkrohling** [comment]
> One comment though: tracer.close() still needs to be called. I ended up putting the JaegerTracer init in a try-resource block.

Even with 0.32.0? I think this shouldn't be necessary on that version, as I implemented a JVM shutdown hook that automatically closes the tracer instances.

**Comment by jpkrohling** [comment]
This is now ready to be merged. @BenHall would you be able to review/merge this PR?

**Comment by BenHall** [comment]
Thanks for the updates!

**Comment by safris** [comment]
> > One comment though: tracer.close() still needs to be called. I ended up putting the JaegerTracer init in a try-resource block.
> 
> Even with 0.32.0? I think this shouldn't be necessary on that version, as I implemented a JVM shutdown hook that automatically closes the tracer instances.

Oh, I was not aware of 0.32.0. Should I also then upgrade the java-opentracing-tutorial to 0.32.0? This will resolve the concern re code coupling to Jaeger.

**Pull request merged**
