### PR TITLE
Add OpenTracing tutorial

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This is basically a copy from https://github.com/jpkrohling/katacoda-scenarios, keeping the current scenario from this repository.

@tedsuo, I remember @bhs saying that there were a couple of issues with the scenarios. It would be nice to sort them out before this gets merged.

Otherwise, we might just want to merge this "as is", and fix possible issues on follow-up PRs.

**Comment by bhs** [comment]
@jpkrohling yeah, I can't recall the precise problem; I think it would be easy to repro, though, just by going through the scenarios (i.e., I hit the issue quickly).

**Comment by jpkrohling** [comment]
Funny, I could swear I could get the first scenario running yesterday, but I did face an issue today:

image

@BenHall, looks like there's still a problem with the file tree. The "copy to editor" seems to work, but the content is not saved in the right path. Do you know what might be going on?

**Comment by BenHall** [comment]
Sorry about this. Let me follow up and see what is happening. It could be the editor issue again

**Comment by jpkrohling** [comment]
@BenHall, would you have news about this one?

**Comment by BenHall** [comment]
We've updated our editor and it's going live on Monday. Once we have this is place it should be more consistent and reliable. I'll then merge the request.

**Pull request merged**
