### PR TITLE
Add lesson01 of OpenTracing python tutorial

### PR DESCRIPTION
**Pull request by pgadige**
Added the first lesson of OpenTracing python tutorial.

Signed-off-by: Pooja Gadige <poojagadige@gmail.com>

### CODE REVIEW

**Comment by pgadige** [comment]
Added the second lesson for OpenTracing python tutorial.

Signed-off-by: Pooja Gadige poojagadige@gmail.com

**Comment by BenHall** [comment]
Thanks @pgadige 

These look great! I just reviewed them. I would just make the changes to the code comments but they're great. Let me know your thoughts and I'll merge them.

**Comment by pgadige** [comment]
Thank you @BenHall for your feedback. I really appreciate it. May I know what changes I need to do to the code comments? Do you want me to remove the comments or rephrase them? Please let me know.

**Comment by BenHall** [comment]
@pgadige  I think removing comments such as `## File:hello.py` as it's only a snippet, not the whole file.

**Comment by BenHall** [comment]
Thank for making the changes and the content! They're now live at https://www.katacoda.com/opentracing

**Comment by pgadige** [comment]
Thank you very much, @BenHall ! I enjoyed creating these scenarios!

**Pull request merged**
